

cork(alwayson, alwayson, uncorked).
cork(alwayson, cstone, uncorked).
cork(alwayson, cscall, uncorked).
cork(alwayson, ipcall, uncorked).
cork(alwayson, camera, uncorked).
cork(alwayson, ringtone, uncorked).
cork(alwayson, alarm, uncorked).
cork(alwayson, voiceui, uncorked).
cork(alwayson, game, uncorked).
cork(alwayson, player, uncorked).
cork(alwayson, flash, uncorked).
cork(alwayson, fmradio, uncorked).
cork(alwayson, event, uncorked).
cork(alwayson, systemsound, uncorked).
cork(alwayson, inputsound, uncorked).
cork(alwayson, othermedia, uncorked).
cork(alwayson, background, uncorked).
cork(alwayson, idle, uncorked).
cork(cstone, alwayson, uncorked).
cork(cstone, cstone, uncorked).
cork(cstone, cscall, uncorked).
cork(cstone, ipcall, uncorked).
cork(cstone, camera, uncorked).
cork(cstone, ringtone, uncorked).
cork(cstone, alarm, uncorked).
cork(cstone, voiceui, uncorked).
cork(cstone, game, uncorked).
cork(cstone, player, uncorked).
cork(cstone, flash, uncorked).
cork(cstone, fmradio, uncorked).
cork(cstone, event, uncorked).
cork(cstone, systemsound, uncorked).
cork(cstone, inputsound, uncorked).
cork(cstone, othermedia, uncorked).
cork(cstone, background, uncorked).
cork(cstone, idle, uncorked).
cork(cscall, alwayson, uncorked).
cork(cscall, cstone, uncorked).
cork(cscall, cscall, uncorked).
cork(cscall, ipcall, uncorked).
cork(cscall, camera, uncorked).
cork(cscall, ringtone, uncorked).
cork(cscall, alarm, uncorked).
cork(cscall, voiceui, uncorked).
cork(cscall, game, uncorked).
cork(cscall, player, uncorked).
cork(cscall, flash, corked).
cork(cscall, fmradio, uncorked).
cork(cscall, event, uncorked).
cork(cscall, systemsound, uncorked).
cork(cscall, inputsound, uncorked).
cork(cscall, othermedia, corked).
cork(cscall, background, uncorked).
cork(cscall, idle, uncorked).
cork(ipcall, alwayson, uncorked).
cork(ipcall, cstone, uncorked).
cork(ipcall, cscall, uncorked).
cork(ipcall, ipcall, uncorked).
cork(ipcall, camera, uncorked).
cork(ipcall, ringtone, uncorked).
cork(ipcall, alarm, uncorked).
cork(ipcall, voiceui, uncorked).
cork(ipcall, game, uncorked).
cork(ipcall, player, uncorked).
cork(ipcall, flash, corked).
cork(ipcall, fmradio, uncorked).
cork(ipcall, event, uncorked).
cork(ipcall, systemsound, uncorked).
cork(ipcall, inputsound, uncorked).
cork(ipcall, othermedia, corked).
cork(ipcall, background, uncorked).
cork(ipcall, idle, uncorked).
cork(camera, alwayson, uncorked).
cork(camera, cstone, uncorked).
cork(camera, cscall, uncorked).
cork(camera, ipcall, uncorked).
cork(camera, camera, uncorked).
cork(camera, ringtone, uncorked).
cork(camera, alarm, uncorked).
cork(camera, voiceui, uncorked).
cork(camera, game, uncorked).
cork(camera, player, uncorked).
cork(camera, flash, corked).
cork(camera, fmradio, uncorked).
cork(camera, event, uncorked).
cork(camera, systemsound, uncorked).
cork(camera, inputsound, uncorked).
cork(camera, othermedia, corked).
cork(camera, background, uncorked).
cork(camera, idle, uncorked).
cork(ringtone, alwayson, uncorked).
cork(ringtone, cstone, uncorked).
cork(ringtone, cscall, uncorked).
cork(ringtone, ipcall, uncorked).
cork(ringtone, camera, uncorked).
cork(ringtone, ringtone, uncorked).
cork(ringtone, alarm, uncorked).
cork(ringtone, voiceui, uncorked).
cork(ringtone, game, uncorked).
cork(ringtone, player, uncorked).
cork(ringtone, flash, uncorked).
cork(ringtone, fmradio, uncorked).
cork(ringtone, event, uncorked).
cork(ringtone, systemsound, uncorked).
cork(ringtone, inputsound, uncorked).
cork(ringtone, othermedia, uncorked).
cork(ringtone, background, uncorked).
cork(ringtone, idle, uncorked).
cork(alarm, alwayson, uncorked).
cork(alarm, cstone, uncorked).
cork(alarm, cscall, uncorked).
cork(alarm, ipcall, uncorked).
cork(alarm, camera, uncorked).
cork(alarm, ringtone, uncorked).
cork(alarm, alarm, uncorked).
cork(alarm, voiceui, uncorked).
cork(alarm, game, uncorked).
cork(alarm, player, uncorked).
cork(alarm, flash, uncorked).
cork(alarm, fmradio, uncorked).
cork(alarm, event, uncorked).
cork(alarm, systemsound, uncorked).
cork(alarm, inputsound, uncorked).
cork(alarm, othermedia, uncorked).
cork(alarm, background, uncorked).
cork(alarm, idle, uncorked).
cork(voiceui, alwayson, uncorked).
cork(voiceui, cstone, uncorked).
cork(voiceui, cscall, uncorked).
cork(voiceui, ipcall, uncorked).
cork(voiceui, camera, uncorked).
cork(voiceui, ringtone, uncorked).
cork(voiceui, alarm, uncorked).
cork(voiceui, voiceui, uncorked).
cork(voiceui, game, uncorked).
cork(voiceui, player, uncorked).
cork(voiceui, flash, corked).
cork(voiceui, fmradio, uncorked).
cork(voiceui, event, uncorked).
cork(voiceui, systemsound, uncorked).
cork(voiceui, inputsound, uncorked).
cork(voiceui, othermedia, corked).
cork(voiceui, background, uncorked).
cork(voiceui, idle, uncorked).
cork(game, alwayson, uncorked).
cork(game, cstone, uncorked).
cork(game, cscall, uncorked).
cork(game, ipcall, uncorked).
cork(game, camera, uncorked).
cork(game, ringtone, uncorked).
cork(game, alarm, uncorked).
cork(game, voiceui, uncorked).
cork(game, game, uncorked).
cork(game, player, uncorked).
cork(game, flash, corked).
cork(game, fmradio, uncorked).
cork(game, event, uncorked).
cork(game, systemsound, uncorked).
cork(game, inputsound, uncorked).
cork(game, othermedia, corked).
cork(game, background, uncorked).
cork(game, idle, uncorked).
cork(player, alwayson, uncorked).
cork(player, cstone, uncorked).
cork(player, cscall, uncorked).
cork(player, ipcall, uncorked).
cork(player, camera, uncorked).
cork(player, ringtone, uncorked).
cork(player, alarm, uncorked).
cork(player, voiceui, uncorked).
cork(player, game, uncorked).
cork(player, player, uncorked).
cork(player, flash, uncorked).
cork(player, fmradio, uncorked).
cork(player, event, uncorked).
cork(player, systemsound, uncorked).
cork(player, inputsound, uncorked).
cork(player, othermedia, uncorked).
cork(player, background, uncorked).
cork(player, idle, uncorked).
cork(flash, alwayson, uncorked).
cork(flash, cstone, uncorked).
cork(flash, cscall, uncorked).
cork(flash, ipcall, uncorked).
cork(flash, camera, uncorked).
cork(flash, ringtone, uncorked).
cork(flash, alarm, uncorked).
cork(flash, voiceui, uncorked).
cork(flash, game, uncorked).
cork(flash, player, uncorked).
cork(flash, flash, uncorked).
cork(flash, fmradio, uncorked).
cork(flash, event, uncorked).
cork(flash, systemsound, uncorked).
cork(flash, inputsound, uncorked).
cork(flash, othermedia, corked).
cork(flash, background, uncorked).
cork(flash, idle, uncorked).
cork(fmradio, alwayson, uncorked).
cork(fmradio, cstone, uncorked).
cork(fmradio, cscall, uncorked).
cork(fmradio, ipcall, uncorked).
cork(fmradio, camera, uncorked).
cork(fmradio, ringtone, uncorked).
cork(fmradio, alarm, uncorked).
cork(fmradio, voiceui, uncorked).
cork(fmradio, game, uncorked).
cork(fmradio, player, uncorked).
cork(fmradio, flash, uncorked).
cork(fmradio, fmradio, uncorked).
cork(fmradio, event, uncorked).
cork(fmradio, systemsound, uncorked).
cork(fmradio, inputsound, uncorked).
cork(fmradio, othermedia, uncorked).
cork(fmradio, background, uncorked).
cork(fmradio, idle, uncorked).
cork(othermedia, alwayson, uncorked).
cork(othermedia, cstone, uncorked).
cork(othermedia, cscall, uncorked).
cork(othermedia, ipcall, uncorked).
cork(othermedia, camera, uncorked).
cork(othermedia, ringtone, uncorked).
cork(othermedia, alarm, uncorked).
cork(othermedia, voiceui, uncorked).
cork(othermedia, game, uncorked).
cork(othermedia, player, uncorked).
cork(othermedia, flash, uncorked).
cork(othermedia, fmradio, uncorked).
cork(othermedia, event, uncorked).
cork(othermedia, systemsound, uncorked).
cork(othermedia, inputsound, uncorked).
cork(othermedia, othermedia, uncorked).
cork(othermedia, background, uncorked).
cork(othermedia, idle, uncorked).
cork(event, alwayson, uncorked).
cork(event, cstone, uncorked).
cork(event, cscall, uncorked).
cork(event, ipcall, uncorked).
cork(event, camera, uncorked).
cork(event, ringtone, uncorked).
cork(event, alarm, uncorked).
cork(event, voiceui, uncorked).
cork(event, game, uncorked).
cork(event, player, uncorked).
cork(event, flash, uncorked).
cork(event, fmradio, uncorked).
cork(event, event, uncorked).
cork(event, systemsound, uncorked).
cork(event, inputsound, uncorked).
cork(event, othermedia, uncorked).
cork(event, background, uncorked).
cork(event, idle, uncorked).
cork(systemsound, alwayson, uncorked).
cork(systemsound, cstone, uncorked).
cork(systemsound, cscall, uncorked).
cork(systemsound, ipcall, uncorked).
cork(systemsound, camera, uncorked).
cork(systemsound, ringtone, uncorked).
cork(systemsound, alarm, uncorked).
cork(systemsound, voiceui, uncorked).
cork(systemsound, game, uncorked).
cork(systemsound, player, uncorked).
cork(systemsound, flash, uncorked).
cork(systemsound, fmradio, uncorked).
cork(systemsound, event, uncorked).
cork(systemsound, systemsound, uncorked).
cork(systemsound, inputsound, uncorked).
cork(systemsound, othermedia, uncorked).
cork(systemsound, background, uncorked).
cork(systemsound, idle, uncorked).
cork(inputsound, alwayson, uncorked).
cork(inputsound, cstone, uncorked).
cork(inputsound, cscall, uncorked).
cork(inputsound, ipcall, uncorked).
cork(inputsound, camera, uncorked).
cork(inputsound, ringtone, uncorked).
cork(inputsound, alarm, uncorked).
cork(inputsound, voiceui, uncorked).
cork(inputsound, game, uncorked).
cork(inputsound, player, uncorked).
cork(inputsound, flash, uncorked).
cork(inputsound, fmradio, uncorked).
cork(inputsound, event, uncorked).
cork(inputsound, systemsound, uncorked).
cork(inputsound, inputsound, uncorked).
cork(inputsound, othermedia, uncorked).
cork(inputsound, background, uncorked).
cork(inputsound, idle, uncorked).
cork(background, alwayson, uncorked).
cork(background, cstone, uncorked).
cork(background, cscall, uncorked).
cork(background, ipcall, uncorked).
cork(background, camera, uncorked).
cork(background, ringtone, uncorked).
cork(background, alarm, uncorked).
cork(background, voiceui, uncorked).
cork(background, game, uncorked).
cork(background, player, uncorked).
cork(background, flash, uncorked).
cork(background, fmradio, uncorked).
cork(background, event, uncorked).
cork(background, systemsound, uncorked).
cork(background, inputsound, uncorked).
cork(background, othermedia, uncorked).
cork(background, background, uncorked).
cork(background, idle, uncorked).
cork(idle, alwayson, uncorked).
cork(idle, cstone, uncorked).
cork(idle, cscall, uncorked).
cork(idle, ipcall, uncorked).
cork(idle, camera, uncorked).
cork(idle, ringtone, uncorked).
cork(idle, alarm, uncorked).
cork(idle, voiceui, uncorked).
cork(idle, game, uncorked).
cork(idle, player, uncorked).
cork(idle, flash, uncorked).
cork(idle, fmradio, uncorked).
cork(idle, event, uncorked).
cork(idle, systemsound, uncorked).
cork(idle, inputsound, uncorked).
cork(idle, othermedia, uncorked).
cork(idle, background, uncorked).
cork(idle, idle, uncorked).
